config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers,skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders,only: [:new, :index, :show, :create]
    #post 'orders/confirm' => 'orders#confirm'
    #get 'orders/complete' => 'orders#complete'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, ]
    #delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    #get 'cart_items' => 'cart_items#index'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end
  
  
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get '/' => 'homes#top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index,:show,:edit,:update]
  end 
  
   
  devise_for :admin,skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  ##小計を求めるメソッド
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end  

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_items, dependent: :destroy
  
  def add_tax_price
    (self.price * 1.10).floor
  end  
  
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card: 0, transfer: 1}
  
  enum is_active: {waiting_for_payment: 0,payment_confirmation: 1,production: 2,shipping_preparation: 3,sent: 4}
  
  has_many :order_details
  has_many :items, through: :order_details
  belongs_to :customer
  

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  enum is_active: {cannot_atart: 0, waiting_for_production: 1, production: 2, production_completed: 3}
  
  belongs_to :order
  belongs_to :item
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  
  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end 
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end 
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    #@total_quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name,:introduction,:price,:image,:is_active,:genre_id, :item_id)
  end
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = @order.order_details
    @total_price = 0
  end
  
  def update
    order = Order.find(params[:id])
    order.update(order_params)
  end 
  
  
  
  private
  
  def order_params
    params.require(:order).permit(:name, :postal_code, :address, :billing_amount, :payment_method, :postage, :is_active, :created_at, :update_at)
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_path
    else
        root_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    #   binding.pry
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    # else
        # root_path
    end
  end
  
  # def index
    # @orders = Order.page(params[:page])
  # end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= @customer.full_name %>さんの会員情報編集
    </div>
  </div>
  

    
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true, method: :patch do |f| %>
    
      <div class="form-group row my-3">
        <%= f.label :customer_id, "会員ID",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
           <%= @customer.id %>
        </div>
      </div>
      
      <div class="form-group row my-3">
        <%= f.label :name, "氏名",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-3">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group row mr-5">
        <%= f.label :name_kana, "フリガナ",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-3">
          <%= f.text_field :last_name_kana, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :first_name_kana, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group row mr-5">
        <%= f.label :postal_code, "郵便番号",class: "col-sm-2 col-form-label" %>
        <div class="col-3">
          <%= f.text_field :postal_code, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group row mr-5">
        <%= f.label :address, "住所",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= f.text_field :address,class: "form-control" %>
        </div>
      </div>
      
      
      <div class="form-group row mr-5">
        <%= f.label :telephone_number, "電話番号",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-3">
          <%= f.text_field :telephone_number, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group row mr-5">
        <%= f.label :email, "メールアドレス",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-3">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group row mr-5">
        <%= f.label :is_active, "会員ステータス",class: "col-sm-2 col-form-label" %>
        <%= f.radio_button :is_active, "有効"  %>
        <%= f.label :is_actice, "有効", value: "有効",class: "col-sm-2 col-form-label" %>
        <%= f.radio_button :is_active, "退会" %>
        <%= f.label :is_active, "退会", value: "退会",class: "col-sm-2 col-form-label" %>
      </div>
      
      <div class="form-group row justify-content-center">
        <div class="col-sm-2">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>
     
    <% end %>
  

  
  
  
  
  
  
  

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h4>会員一覧</h4>
    </div>
  </div>
  
    
  <table class="table">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.full_name %>
            <% end %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_active == true %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      <% end %>
      <%#= paginate @customers %>
    </tbody>
  </table>
  

  <%= paginate @customers %>
  
  
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 my-4">
      <h4><%= @customer.full_name %>さんの会員詳細</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <th><%= @customer.id %></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= @customer.full_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= @customer.full_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th><%= @customer.postal_code %></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= @customer.address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= @customer.telephone_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= @customer.email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th>
              <% if @customer.is_active == true %>
                有効
              <% else %>
                退会
              <% end %>
            </th>
            
          </tr>
          <tr>
            <th>
              <%= link_to "編集する",edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
              <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    
  
</div>