config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers,skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders,only: [:new, :index, :show, :create]
    #post 'orders/confirm' => 'orders#confirm'
    #get 'orders/complete' => 'orders#complete'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, ]
    #delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    #get 'cart_items' => 'cart_items#index'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end
  
  
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get '/' => 'homes#top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index,:show,:edit,:update]
  end 
  
   
  devise_for :admin,skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  ##小計を求めるメソッド
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end  

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_items, dependent: :destroy
  
  def add_tax_price
    (self.price * 1.10).floor
  end  
  
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card: 0, transfer: 1}
  
  enum is_active: {waiting_for_payment: 0,payment_confirmation: 1,production: 2,shipping_preparation: 3,sent: 4}
  
  has_many :order_details
  has_many :items, through: :order_details
  belongs_to :customer
  

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  enum is_active: {cannot_atart: 0, waiting_for_production: 1, production: 2, production_completed: 3}
  
  belongs_to :order
  belongs_to :item
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  
  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end 
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end 
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    #@total_quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name,:introduction,:price,:image,:is_active,:genre_id, :item_id)
  end
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = @order.order_details
    @total_price = 0
  end
  
  def update
    order = Order.find(params[:id])
    order.update(order_params)
  end 
  
  
  
  private
  
  def order_params
    params.require(:order).permit(:name, :postal_code, :address, :billing_amount, :payment_method, :postage, :is_active, :created_at, :update_at)
  end
  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_path
    else
        root_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    #   binding.pry
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    # else
        # root_path
    end
  end
  
  # def index
    # @orders = Order.page(params[:page])
  # end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 my-5 ">
      <h4>ジャンル編集</h4>
    </div>
  </div>
  
     
    
  <%= form_with model: @genre, url: admin_genre_path, local: true, method: :PATCH do |f| %>
    <div class="row">
      <div class="col-2">
        <div class="form-group mr-5"> 
         <%= f.label :genre, "ジャンル名" %>
        </div>
      </div>
    
      <div class="col-2">
        <div class="form-group mr-5">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    
      <div class="col-2">
        <div class="form-group mr-5">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>
      <div class="col-6">
        
      </div>
    </div>  
    
     
  <% end %>
  
</div>
 

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-5">
      <h4>ジャンル一覧・追加</h4>
    </div>
  </div>
  
  
   
  <%= form_with model: @genre, url: admin_genres_path, local: true, method: :POST do |f| %>
    <div class="row">
      <div class="col-2">
        <div class="form-group mr-5 mt-5">
          <%= f.label :genre, "ジャンル名" %>
        </div>
      </div>
      <div class="col-2">
        <div class="form-group mr-5 mt-5">
            <%= f.text_field :name, placeholder: "ジャンル名", class: "form-control" %>
        </div>
      </div>
      <div class="col-2">
        <div class="form-group mr-5 mt-5">
          <%= f.submit '新規登録', class: "btn btn-success" %>
        </div>
      </div>
      <div class="col-6">
      </div>
    </div>
  <% end %>
      

 
  
  <div clss="row">
    <div class="col-4 mt-5">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td class="text-right">
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
 
    </div>
  </div>
  
   
  
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-5">
      <h4>商品編集</h4>
    </div>
  </div>
  
 

    
  <%= form_with model: @item, url: admin_item_path(@item.id), local: true, method: :PATCH do |f| %>
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :image, "商品画像" %>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-gourp">
          <%= f.file_field :image,accept: "image/*",class: "form-control-file image" %>
        </div>
      </div>
    </div>
      
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :name, "商品名" %>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>
     
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :introduction, "商品説明"%>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-group">
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
      </div>
    </div>
      
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :genre, "ジャンル"%>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-group">
          <%= f.collection_select :genre_id, @genre, :id, :name, :include_blank => "選択してください" %>
        </div>
      </div>
    </div>
      
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :proce, "税抜価格"%>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-group">
          <%= f.text_field :price, class: "form-control" %>円
        </div>
      </div>
    </div>
      
    <div class="row">
      <div class="col-2 offset-2 text-left">
        <div class="form-group">
          <%= f.label :is_active, "販売ステータス"%>
        </div>
      </div>
      <div class="col ml-5">
        <div class="form-group">
          <%= f.radio_button :is_active, "販売中"  %>
          <%= f.label :is_actice, "販売中", value: "販売中",class: "col-form-label" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= f.radio_button :is_active, "販売停止中" %>
          <%= f.label :is_active, "販売停止中", value: "販売停止中",class: "col-form-label" %>
        </div>
      </div>
    </div>
      
    <div class="row text-center">
      <div class="col">
        <div class="form-gruop row justify-content-center">
          <%= f.submit '変更を保存', class: "btn btn-success" %>
        </div>
      </div>
    </div>
    
          
     
  <% end %>
  
 
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 my-3">
      <h4>商品一覧</h4>
    </div>
    <div class="col-2 offset-6 my-3">
      <%= link_to new_admin_item_path, class: 'text-light' do %>
        <i class="fas fa-plus-circle fa-3x"></i>
        <!--<i class="fa-light fa-circle-plus"></i>-->
        <!--<i class="fa-thin fa-circle-plus"></i>-->
      <% end %>
    </div>
  </div>
  
    
  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td>
            <%= item.id %>
          </td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td>
            <%= item.price %>
          </td>
          <td>
            <%= item.genre.name %>
          </td>
          <td>
            <%= item.is_active %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
   
  
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-5">
      <h4>商品新規登録</h4>
    </div>
  </div>
  

      
    
      <%= form_with model: @item, url: admin_items_path, local: true, method: :POST do |f| %>
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :image, "商品画像" %>
            </div>
          </div>
          
          <div class="col ml-5">
            <div class="form-group">
            <%= f.file_field :image,accept: "image/*",class: "form-control-file image" %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :name, "商品名" %>
            </div>
          </div>
          <div class="col ml-5">
            <div class="form-group">
              <%= f.text_field :name,placeholder: "商品名", class: "form-control col-6" %>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :introduction, "商品説明" %>
            </div>
          </div>
          <div class="col ml-5">
            <div class="form-group">
              <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class: "form-control col-6" %>
            </div>
          </div>
        </div>  
        
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :genre, "ジャンル名" %>
            </div>
          </div>
          <div class="col ml-5">
            <div class="form-group">
              <%= f.collection_select :genre_id, @genre, :id, :name, :include_blank => "選択してください" %>
            </div>
          </div>
        </div>
      
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :price, "税抜価格" %>
            </div>
          </div>
          <div class="col ml-5 flex-row">
            <div class="form-group">
              <%= f.text_field :price, placeholder: "1000", class: "form-control col-6" %><span>円</span>
            </div>
          </div>
        </div>
        
        <div class="row">
          <div class="col-2 offset-2 text-left">
            <div class="form-group">
              <%= f.label :is_active, "販売ステータス"%>
            </div>
          </div>
          <div class="col ml-5">
            <div class="form-group">
              <%= f.radio_button :is_active, "販売中"  %>
              <%= f.label :is_actice, "販売中", value: "販売中" %>
              <%= f.radio_button :is_active, "販売停止中" %>
              <%= f.label :is_active, "販売停止中", value: "販売停止中" %>
            </div>
          </div>
        </div>
        
        <div class= "row text-center">
          <dic class="col">
            <div class="form-group">
              <%= f.submit '新規登録', class: "btn btn-success" %>
            </div>
          </div>
        </div>
         
     
      <% end %>
  
      

  
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-5">
      <h4>商品詳細</h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
        <% if @item.image.attached? %>
          <%= image_tag @item.image, size: "200x200"  %>
        <% else %>
          <%= image_tag 'no_image.jpeg', size: "200x200" %>
        <% end %>
    </div>
    
    <div class="col-md-8">
      <table class="table">
        <tbody>
          <tr>
            <th>商品名</th>
            <th><%= @item.name %></th>
          </tr>
          <tr>
            <th>商品説明</th>
            <th><%= @item.introduction %></th>
          </tr>
          <tr>
            <th>ジャンル</th>
            <th><%= @item.genre.name %></th>
          </tr>
          <tr>
            <th>税込価格</br>
            (税抜価格)</th>
            <th><%= @item.add_tax_price.to_s(:delimited) %>
            (<%= @item.price.to_s(:delimited) %>)円</th>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td>
              <% if @item.is_active == true %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
          <tr>
            <th>
              <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
            </th>
          </tr>
          
        </tbody>
      </table>
    </div>
  
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h4>注文履歴詳細</h4>
    </div>
  </div>
  
    
  <div class="row">
    <div class="col-10">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>購入者</th>
            <th><%= @order.customer.last_name + @order.customer.first_name %></th>
          </tr>
          <tr>
            <th>注文日</th>
            <th><%= l @order.created_at %></th>
          </tr>
          <tr>
            <th>配送先</th>
            <th><%= @order.address %></th>
          </tr>
          <tr>
            <th>支払方法</th>
            <th><%= @order.payment_method_i18n %></th>
          </tr>
          <tr>
            <%= form_with model: @order, url: admin_order_path(@order.id), local: true, method: :PATCH do |f| %>
              <th><%= f.label :is_active, "注文ステータス" %></th>
              <th><%= f.select :is_active, options_from_collection_for_select(@orders, :id, :is_active_i18n) %></th>
            <!--<th>注文ステータス</th>-->
            <!--<th><%#= @order.is_active %></th>-->
              <th><%= f.submit "更新", class: "btn btn-success" %></th>
            <% end %>
          </tr>
        </thead>
      </table>
    </div>
  </div>
      
  <div class="row">
    <div class="col-9">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td>
                <%= order_detail.item.price %>
              </td>
              <td>
                <%= order_detail.quantity %>
              </td>
              <td>
                <%= order_detail.quantity * order_detail.item.price %>
              </td>
              <td>
                <%= form_with model: @order_detail, url: admin_order_detail_path(order_detail.id), local: true, method: :PATCH do |f| %>
                  <%#= f.radio_button :is_active %>
                  <%#= f.label :is_active, "製作ステータス" %>
                  <%= f.select :is_active, options_from_collection_for_select(@order_details, :id, :is_active_i18n) %>
                  <%#= order_detail.is_active %>
                  <%= f.submit "更新", class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="col-3 d-flex align-items-end">
      <table class="table">
          <tr>
            <th>商品合計</th>
            <td>
              <% @order.order_details.each do |order_detail| %>
                <% @total_price += order_detail.quantity * order_detail.item.price %>
              <% end %>
              <%= @total_price %>円
            </td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.postage %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td>
              <%= (@order.postage + @total_price).to_s(:delimited) %>円
            </td>
          </tr>
      
      </table>
    </div>
  </div>
</div>