config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers,skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders,only: [:new, :index, :show, :create]
    #post 'orders/confirm' => 'orders#confirm'
    #get 'orders/complete' => 'orders#complete'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, ]
    #delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    #get 'cart_items' => 'cart_items#index'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe'
    patch 'customers/withdraw'
  end
  
  
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    get '/' => 'homes#top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :customers, only: [:index,:show,:edit,:update]
  end 
  
   
  devise_for :admin,skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + '' + address + '' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  ##小計を求めるメソッド
  def subtotal
    item.add_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end  

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  belongs_to :genre
  
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_items, dependent: :destroy
  
  def add_tax_price
    (self.price * 1.10).floor
  end  
  
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit_card: 0, transfer: 1}
  
  enum is_active: {waiting_for_payment: 0,payment_confirmation: 1,production: 2,shipping_preparation: 3,sent: 4}
  
  has_many :order_details
  has_many :items, through: :order_details
  belongs_to :customer
  

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  enum is_active: {cannot_atart: 0, waiting_for_production: 1, production: 2, production_completed: 3}
  
  belongs_to :order
  belongs_to :item
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  
  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end 
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end 
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    #@total_quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name,:introduction,:price,:image,:is_active,:genre_id, :item_id)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
        admin_path
    else
        root_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    #   binding.pry
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    # else
        # root_path
    end
  end
  
  # def index
    # @orders = Order.page(params[:page])
  # end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span>Logo</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto ">
              <% if admin_signed_in? %>
              <li>
                <%= link_to admin_items_path, class: 'nav-link' do %>
                  商品一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_customers_path ,class: 'nav-link' do %>
                  会員一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_path, class: 'nav-link' do %>
                  注文履歴一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_genres_path, class: 'nav-link' do %>
                  ジャンル一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete ,class: 'nav-link' do %>
                  ログアウト
                <% end %>
              </li>
              
              <% elsif customer_signed_in? %>
              <li>
                <%= link_to customers_my_page_path, class: 'nav-link' do %>
                  マイページ
                <% end %>
              </li>
              <li>
                <%= link_to items_path ,class: 'nav-link' do %>
                  商品一覧
                <% end %>
              </li>
              <li>
                <%= link_to cart_items_path, class: 'nav-link' do %>
                  カート
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete ,class: 'nav-link' do %>
                  ログアウト
                <% end %>
              </li>
              
              <% else %>
              <li>
                <%= link_to about_path, class: 'nav-link' do %>
                  about
                <% end %>
              </li>
              <li>
                <%= link_to items_path, class: 'nav-link' do %>
                  商品一覧
                <% end %>
              </li>
              <Li>
                <%= link_to new_customer_registration_path, class: 'nav-link' do %>
                  新規登録
                <% end %>
              </Li>
              <li>
                <%= link_to new_customer_session_path, class: 'nav-link' do %>
                  ログイン
                <% end %>
              </li>
              <% end %>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>